spring.application.name=ironlog

spring.datasource.url=jdbc:mysql://localhost:3306/ironlog
spring.datasource.username=root
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}
